apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels: 
    env: production
spec:
  template:
      metadata:
          name: nginx-2
          labels:
            env: production
      spec:
          containers:
            - name: nginx-container
              image: nginx:1.7.1
  replicas: 4
  selector:
    matchLabels:
      env: production 
                
