apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels: 
    env: sim
spec:
  containers: 
    - name: simple-webapp-color1
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: DB_Password
          valueFrom:
            secretKeyRef:
              key: DB_Password
              name: app-secret
 