apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - protocol: TCP
      nodePort: 31001
      port: 80
      targetPort: 80